[package]
name = "rlf"
version = "0.1.0"
edition = "2024"

[dependencies]
bon = "3.8"
thiserror = "2.0"
serde = { version = "1.0", features = ["derive"] }
const-fnv1a-hash = "1.1"

[dev-dependencies]
insta = "1.42"
